# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/javier/z/dev/git/JMC-IMPEDANCIMETER-DAQ/hp4192a/gui/main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HP4192A(object):
    def setupUi(self, HP4192A):
        HP4192A.setObjectName(_fromUtf8("hp4192a"))
        HP4192A.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./gui/images/logo-symbol-64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HP4192A.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(HP4192A)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.experimental_setup = QtGui.QWidget()
        self.experimental_setup.setObjectName(_fromUtf8("experimental_setup"))
        self.gridLayout_15 = QtGui.QGridLayout(self.experimental_setup)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gb_plota = QtGui.QGroupBox(self.experimental_setup)
        self.gb_plota.setObjectName(_fromUtf8("gb_plota"))
        self.gridLayout_15.addWidget(self.gb_plota, 0, 1, 1, 3)
        self.gb_lcd_freq = QtGui.QGroupBox(self.experimental_setup)
        self.gb_lcd_freq.setMaximumSize(QtCore.QSize(16777215, 100))
        self.gb_lcd_freq.setObjectName(_fromUtf8("gb_lcd_freq"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gb_lcd_freq)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lcd_freq = QtGui.QLCDNumber(self.gb_lcd_freq)
        self.lcd_freq.setObjectName(_fromUtf8("lcd_freq"))
        self.gridLayout_4.addWidget(self.lcd_freq, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.gb_lcd_freq, 2, 3, 1, 1)
        self.gb_plotb = QtGui.QGroupBox(self.experimental_setup)
        self.gb_plotb.setObjectName(_fromUtf8("gb_plotb"))
        self.gridLayout_15.addWidget(self.gb_plotb, 1, 1, 1, 3)
        self.gb_lcd_a = QtGui.QGroupBox(self.experimental_setup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_lcd_a.sizePolicy().hasHeightForWidth())
        self.gb_lcd_a.setSizePolicy(sizePolicy)
        self.gb_lcd_a.setMaximumSize(QtCore.QSize(16777215, 100))
        self.gb_lcd_a.setObjectName(_fromUtf8("gb_lcd_a"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gb_lcd_a)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lcd_a = QtGui.QLCDNumber(self.gb_lcd_a)
        self.lcd_a.setObjectName(_fromUtf8("lcd_a"))
        self.gridLayout_2.addWidget(self.lcd_a, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.gb_lcd_a, 2, 1, 1, 1)
        self.gb_lcd_b = QtGui.QGroupBox(self.experimental_setup)
        self.gb_lcd_b.setMaximumSize(QtCore.QSize(16777215, 100))
        self.gb_lcd_b.setObjectName(_fromUtf8("gb_lcd_b"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gb_lcd_b)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lcd_b = QtGui.QLCDNumber(self.gb_lcd_b)
        self.lcd_b.setObjectName(_fromUtf8("lcd_b"))
        self.gridLayout_3.addWidget(self.lcd_b, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.gb_lcd_b, 2, 2, 1, 1)
        self.tbx_settings = QtGui.QToolBox(self.experimental_setup)
        self.tbx_settings.setMinimumSize(QtCore.QSize(260, 0))
        self.tbx_settings.setMaximumSize(QtCore.QSize(260, 16777215))
        self.tbx_settings.setStyleSheet(_fromUtf8(""))
        self.tbx_settings.setObjectName(_fromUtf8("tbx_settings"))
        self.plot_settings = QtGui.QWidget()
        self.plot_settings.setGeometry(QtCore.QRect(0, 0, 260, 415))
        self.plot_settings.setObjectName(_fromUtf8("plot_settings"))
        self.gridLayout_7 = QtGui.QGridLayout(self.plot_settings)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gb_plot_a_channels = QtGui.QGroupBox(self.plot_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_plot_a_channels.sizePolicy().hasHeightForWidth())
        self.gb_plot_a_channels.setSizePolicy(sizePolicy)
        self.gb_plot_a_channels.setMaximumSize(QtCore.QSize(250, 16777215))
        self.gb_plot_a_channels.setObjectName(_fromUtf8("gb_plot_a_channels"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gb_plot_a_channels)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label = QtGui.QLabel(self.gb_plot_a_channels)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.cbx_x_plot_a = QtGui.QComboBox(self.gb_plot_a_channels)
        self.cbx_x_plot_a.setObjectName(_fromUtf8("cbx_x_plot_a"))
        self.cbx_x_plot_a.addItem(_fromUtf8(""), 'a')
        self.cbx_x_plot_a.addItem(_fromUtf8(""), 'b')
        self.cbx_x_plot_a.addItem(_fromUtf8(""), 'f')
        self.cbx_x_plot_a.setCurrentIndex(0)
        self.gridLayout_9.addWidget(self.cbx_x_plot_a, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gb_plot_a_channels)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_9.addWidget(self.label_2, 1, 0, 1, 1)
        self.cbx_y_plot_a = QtGui.QComboBox(self.gb_plot_a_channels)
        self.cbx_y_plot_a.setObjectName(_fromUtf8("cbx_y_plot_a"))
        self.cbx_y_plot_a.addItem(_fromUtf8(""), 'a')
        self.cbx_y_plot_a.addItem(_fromUtf8(""), 'b')
        self.cbx_y_plot_a.addItem(_fromUtf8(""), 'f')
        self.cbx_y_plot_a.setCurrentIndex(1)
        self.gridLayout_9.addWidget(self.cbx_y_plot_a, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.gb_plot_a_channels, 0, 0, 1, 1)
        self.gb_plot_b_channels = QtGui.QGroupBox(self.plot_settings)
        self.gb_plot_b_channels.setMaximumSize(QtCore.QSize(250, 16777215))
        self.gb_plot_b_channels.setObjectName(_fromUtf8("gb_plot_b_channels"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gb_plot_b_channels)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_3 = QtGui.QLabel(self.gb_plot_b_channels)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.cbx_x_plot_b = QtGui.QComboBox(self.gb_plot_b_channels)
        self.cbx_x_plot_b.addItem(_fromUtf8(""), 'a')
        self.cbx_x_plot_b.addItem(_fromUtf8(""), 'b')
        self.cbx_x_plot_b.addItem(_fromUtf8(""), 'f')
        self.cbx_x_plot_b.setCurrentIndex(0)
        self.cbx_x_plot_b.setObjectName(_fromUtf8("cbx_x_plot_b"))
        self.gridLayout_8.addWidget(self.cbx_x_plot_b, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gb_plot_b_channels)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 1, 0, 1, 1)
        self.cbx_y_plot_b = QtGui.QComboBox(self.gb_plot_b_channels)
        self.cbx_y_plot_b.addItem(_fromUtf8(""), 'a')
        self.cbx_y_plot_b.addItem(_fromUtf8(""), 'b')
        self.cbx_y_plot_b.addItem(_fromUtf8(""), 'f')
        self.cbx_y_plot_b.setCurrentIndex(2)
        self.cbx_y_plot_b.setObjectName(_fromUtf8("cbx_y_plot_b"))
        self.gridLayout_8.addWidget(self.cbx_y_plot_b, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.gb_plot_b_channels, 1, 0, 1, 1)
        self.gb_impedance = QtGui.QGroupBox(self.plot_settings)
        self.gb_impedance.setMaximumSize(QtCore.QSize(250, 16777215))
        self.gb_impedance.setCheckable(True)
        self.gb_impedance.setChecked(False)
        self.gb_impedance.setObjectName(_fromUtf8("gb_impedance"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gb_impedance)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_5 = QtGui.QLabel(self.gb_impedance)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.dsb_impedance_area = QtGui.QDoubleSpinBox(self.gb_impedance)
        self.dsb_impedance_area.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.dsb_impedance_area.setObjectName(_fromUtf8("dsb_impedance_area"))
        self.gridLayout_6.addWidget(self.dsb_impedance_area, 0, 1, 1, 1)
        self.cbx_impedance_area_units = QtGui.QComboBox(self.gb_impedance)
        self.cbx_impedance_area_units.setObjectName(_fromUtf8("cbx_impedance_area_units"))
        self.cbx_impedance_area_units.addItem(_fromUtf8(""))
        self.cbx_impedance_area_units.addItem(_fromUtf8(""))
        self.cbx_impedance_area_units.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cbx_impedance_area_units, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.gb_impedance)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.dsb_impedance_thickness = QtGui.QDoubleSpinBox(self.gb_impedance)
        self.dsb_impedance_thickness.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.dsb_impedance_thickness.setPrefix(_fromUtf8(""))
        self.dsb_impedance_thickness.setSuffix(_fromUtf8(""))
        self.dsb_impedance_thickness.setObjectName(_fromUtf8("dsb_impedance_thickness"))
        self.gridLayout_6.addWidget(self.dsb_impedance_thickness, 1, 1, 1, 1)
        self.cbx_impedance_thickness_units = QtGui.QComboBox(self.gb_impedance)
        self.cbx_impedance_thickness_units.setObjectName(_fromUtf8("cbx_impedance_thickness_units"))
        self.cbx_impedance_thickness_units.addItem(_fromUtf8(""))
        self.cbx_impedance_thickness_units.addItem(_fromUtf8(""))
        self.cbx_impedance_thickness_units.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cbx_impedance_thickness_units, 1, 2, 1, 1)
        self.gridLayout_7.addWidget(self.gb_impedance, 2, 0, 1, 1)
        self.gb_capacitance = QtGui.QGroupBox(self.plot_settings)
        self.gb_capacitance.setMaximumSize(QtCore.QSize(250, 16777215))
        self.gb_capacitance.setCheckable(True)
        self.gb_capacitance.setChecked(False)
        self.gb_capacitance.setObjectName(_fromUtf8("gb_capacitance"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gb_capacitance)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_7 = QtGui.QLabel(self.gb_capacitance)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.dsb_capacitance_area = QtGui.QDoubleSpinBox(self.gb_capacitance)
        self.dsb_capacitance_area.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.dsb_capacitance_area.setMinimum(-999999999.0)
        self.dsb_capacitance_area.setMaximum(999999999.0)
        self.dsb_capacitance_area.setSingleStep(0.1)
        self.dsb_capacitance_area.setProperty("value", 5.0)
        self.dsb_capacitance_area.setObjectName(_fromUtf8("dsb_capacitance_area"))
        self.gridLayout_5.addWidget(self.dsb_capacitance_area, 0, 1, 1, 1)
        self.cbx_capacitance_area_units = QtGui.QComboBox(self.gb_capacitance)
        self.cbx_capacitance_area_units.setObjectName(_fromUtf8("cbx_capacitance_area_units"))
        self.cbx_capacitance_area_units.addItem(_fromUtf8(""))
        self.cbx_capacitance_area_units.addItem(_fromUtf8(""))
        self.cbx_capacitance_area_units.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cbx_capacitance_area_units, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.gb_capacitance)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.dsb_capacitance_e0 = QtGui.QDoubleSpinBox(self.gb_capacitance)
        self.dsb_capacitance_e0.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.dsb_capacitance_e0.setDecimals(11)
        self.dsb_capacitance_e0.setProperty("value", 8e-06)
        self.dsb_capacitance_e0.setObjectName(_fromUtf8("dsb_capacitance_e0"))
        self.gridLayout_5.addWidget(self.dsb_capacitance_e0, 1, 1, 1, 1)
        self.cbx_capacitance_e0_units = QtGui.QComboBox(self.gb_capacitance)
        self.cbx_capacitance_e0_units.setObjectName(_fromUtf8("cbx_capacitance_e0_units"))
        self.cbx_capacitance_e0_units.addItem(_fromUtf8(""))
        self.cbx_capacitance_e0_units.addItem(_fromUtf8(""))
        self.cbx_capacitance_e0_units.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cbx_capacitance_e0_units, 1, 2, 1, 1)
        self.gridLayout_7.addWidget(self.gb_capacitance, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 72, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 4, 0, 1, 1)
        self.tbx_settings.addItem(self.plot_settings, _fromUtf8(""))
        self.save_data_settings = QtGui.QWidget()
        self.save_data_settings.setGeometry(QtCore.QRect(0, 0, 260, 415))
        self.save_data_settings.setObjectName(_fromUtf8("save_data_settings"))
        self.gridLayout_16 = QtGui.QGridLayout(self.save_data_settings)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_18 = QtGui.QLabel(self.save_data_settings)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_16.addWidget(self.label_18, 0, 0, 1, 1)
        self.le_outputfile = QtGui.QLineEdit(self.save_data_settings)
        self.le_outputfile.setObjectName(_fromUtf8("le_outputfile"))
        self.gridLayout_16.addWidget(self.le_outputfile, 1, 0, 1, 1)
        self.cbx_file_display_b_order = QtGui.QComboBox(self.save_data_settings)
        self.cbx_file_display_b_order.setObjectName(_fromUtf8("cbx_file_display_b_order"))
        self.gridLayout_16.addWidget(self.cbx_file_display_b_order, 5, 0, 1, 1)
        self.cbx_file_display_a_order = QtGui.QComboBox(self.save_data_settings)
        self.cbx_file_display_a_order.setObjectName(_fromUtf8("cbx_file_display_a_order"))
        self.gridLayout_16.addWidget(self.cbx_file_display_a_order, 3, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.save_data_settings)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_16.addWidget(self.label_20, 4, 0, 1, 1)
        self.tlb_output_file = QtGui.QToolButton(self.save_data_settings)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./gui/images/folder_black.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_output_file.setIcon(icon1)
        self.tlb_output_file.setObjectName(_fromUtf8("tlb_output_file"))
        self.gridLayout_16.addWidget(self.tlb_output_file, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.save_data_settings)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_16.addWidget(self.label_19, 2, 0, 1, 1)

        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem1, 8, 0, 1, 1)
        self.tbx_settings.addItem(self.save_data_settings, _fromUtf8(""))
        self.control = QtGui.QWidget()
        self.control.setGeometry(QtCore.QRect(0, 0, 260, 415))
        self.control.setObjectName(_fromUtf8("control"))
        self.gridLayout_17 = QtGui.QGridLayout(self.control)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.pb_start = QtGui.QPushButton(self.control)
        self.pb_start.setObjectName(_fromUtf8("pb_start"))
        self.gridLayout_17.addWidget(self.pb_start, 1, 0, 1, 2)
        self.pb_monitor = QtGui.QPushButton(self.control)
        self.pb_monitor.setObjectName(_fromUtf8("pb_monitor"))
        self.gridLayout_17.addWidget(self.pb_monitor, 0, 0, 1, 1)
        self.pb_reset = QtGui.QPushButton(self.control)
        self.pb_reset.setObjectName(_fromUtf8("pb_reset"))
        self.gridLayout_17.addWidget(self.pb_reset, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 344, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem2, 2, 0, 1, 2)
        self.tbx_settings.addItem(self.control, _fromUtf8(""))
        self.gridLayout_15.addWidget(self.tbx_settings, 0, 0, 3, 1)
        self.tabWidget.addTab(self.experimental_setup, _fromUtf8(""))
        self.config_inputs = QtGui.QWidget()
        self.config_inputs.setObjectName(_fromUtf8("config_inputs"))
        self.gb_serial_config = QtGui.QGroupBox(self.config_inputs)
        self.gb_serial_config.setGeometry(QtCore.QRect(10, 0, 250, 193))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_serial_config.sizePolicy().hasHeightForWidth())
        self.gb_serial_config.setSizePolicy(sizePolicy)
        self.gb_serial_config.setMinimumSize(QtCore.QSize(250, 0))
        self.gb_serial_config.setObjectName(_fromUtf8("gb_serial_config"))
        self.gridLayout_14 = QtGui.QGridLayout(self.gb_serial_config)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.lb_serial_stopbits = QtGui.QLabel(self.gb_serial_config)
        self.lb_serial_stopbits.setObjectName(_fromUtf8("lb_serial_stopbits"))
        self.gridLayout_14.addWidget(self.lb_serial_stopbits, 3, 0, 1, 1)
        self.lb_serial_parity = QtGui.QLabel(self.gb_serial_config)
        self.lb_serial_parity.setObjectName(_fromUtf8("lb_serial_parity"))
        self.gridLayout_14.addWidget(self.lb_serial_parity, 2, 0, 1, 1)
        self.lb_serial_bytesize = QtGui.QLabel(self.gb_serial_config)
        self.lb_serial_bytesize.setObjectName(_fromUtf8("lb_serial_bytesize"))
        self.gridLayout_14.addWidget(self.lb_serial_bytesize, 4, 0, 1, 1)
        self.lb_serial_baudrate = QtGui.QLabel(self.gb_serial_config)
        self.lb_serial_baudrate.setObjectName(_fromUtf8("lb_serial_baudrate"))
        self.gridLayout_14.addWidget(self.lb_serial_baudrate, 1, 0, 1, 1)
        self.lb_serial_timeout = QtGui.QLabel(self.gb_serial_config)
        self.lb_serial_timeout.setObjectName(_fromUtf8("lb_serial_timeout"))
        self.gridLayout_14.addWidget(self.lb_serial_timeout, 5, 0, 1, 1)
        self.cbx_serial_port = QtGui.QComboBox(self.gb_serial_config)
        self.cbx_serial_port.setObjectName(_fromUtf8("cbx_serial_port"))
        self.gridLayout_14.addWidget(self.cbx_serial_port, 0, 2, 1, 1)
        self.sp_serial_timeout = QtGui.QSpinBox(self.gb_serial_config)
        self.sp_serial_timeout.setMinimum(1)
        self.sp_serial_timeout.setProperty("value", 2)
        self.sp_serial_timeout.setObjectName(_fromUtf8("sp_serial_timeout"))
        self.gridLayout_14.addWidget(self.sp_serial_timeout, 5, 2, 1, 1)
        self.lb_serial_port = QtGui.QLabel(self.gb_serial_config)
        self.lb_serial_port.setObjectName(_fromUtf8("lb_serial_port"))
        self.gridLayout_14.addWidget(self.lb_serial_port, 0, 0, 1, 1)
        self.cbx_serial_baudrates = QtGui.QComboBox(self.gb_serial_config)
        self.cbx_serial_baudrates.setObjectName(_fromUtf8("cbx_serial_baudrates"))
        self.gridLayout_14.addWidget(self.cbx_serial_baudrates, 1, 2, 1, 1)
        self.cbx_serial_parities = QtGui.QComboBox(self.gb_serial_config)
        self.cbx_serial_parities.setObjectName(_fromUtf8("cbx_serial_parities"))
        self.gridLayout_14.addWidget(self.cbx_serial_parities, 2, 2, 1, 1)
        self.cbx_serial_stopbits = QtGui.QComboBox(self.gb_serial_config)
        self.cbx_serial_stopbits.setObjectName(_fromUtf8("cbx_serial_stopbits"))
        self.gridLayout_14.addWidget(self.cbx_serial_stopbits, 3, 2, 1, 1)
        self.cbx_serial_bytesizes = QtGui.QComboBox(self.gb_serial_config)
        self.cbx_serial_bytesizes.setObjectName(_fromUtf8("cbx_serial_bytesizes"))
        self.gridLayout_14.addWidget(self.cbx_serial_bytesizes, 4, 2, 1, 1)
        self.gb_error_filters = QtGui.QGroupBox(self.config_inputs)
        self.gb_error_filters.setGeometry(QtCore.QRect(10, 210, 647, 142))
        self.gb_error_filters.setObjectName(_fromUtf8("gb_error_filters"))
        self.gridLayout_13 = QtGui.QGridLayout(self.gb_error_filters)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gb_display_a_error_filter = QtGui.QGroupBox(self.gb_error_filters)
        self.gb_display_a_error_filter.setObjectName(_fromUtf8("gb_display_a_error_filter"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gb_display_a_error_filter)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_9 = QtGui.QLabel(self.gb_display_a_error_filter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_10.addWidget(self.label_9, 0, 0, 1, 1)
        self.dsb_da_valid_range = QtGui.QDoubleSpinBox(self.gb_display_a_error_filter)
        self.dsb_da_valid_range.setObjectName(_fromUtf8("dsb_da_valid_range"))
        self.gridLayout_10.addWidget(self.dsb_da_valid_range, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gb_display_a_error_filter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_10.addWidget(self.label_11, 1, 0, 1, 1)
        self.sb_da_poly_order = QtGui.QSpinBox(self.gb_display_a_error_filter)
        self.sb_da_poly_order.setObjectName(_fromUtf8("sb_da_poly_order"))
        self.gridLayout_10.addWidget(self.sb_da_poly_order, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gb_display_a_error_filter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_10.addWidget(self.label_12, 2, 0, 1, 1)
        self.sb_da_sample_values = QtGui.QSpinBox(self.gb_display_a_error_filter)
        self.sb_da_sample_values.setObjectName(_fromUtf8("sb_da_sample_values"))
        self.gridLayout_10.addWidget(self.sb_da_sample_values, 2, 1, 1, 1)
        self.gridLayout_13.addWidget(self.gb_display_a_error_filter, 0, 0, 1, 1)
        self.gb_display_b_error_filter = QtGui.QGroupBox(self.gb_error_filters)
        self.gb_display_b_error_filter.setObjectName(_fromUtf8("gb_display_b_error_filter"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gb_display_b_error_filter)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_10 = QtGui.QLabel(self.gb_display_b_error_filter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_11.addWidget(self.label_10, 0, 0, 1, 1)
        self.dsb_db_valid_range = QtGui.QDoubleSpinBox(self.gb_display_b_error_filter)
        self.dsb_db_valid_range.setObjectName(_fromUtf8("dsb_db_valid_range"))
        self.gridLayout_11.addWidget(self.dsb_db_valid_range, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gb_display_b_error_filter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_11.addWidget(self.label_13, 1, 0, 1, 1)
        self.sb_db_poly_order = QtGui.QSpinBox(self.gb_display_b_error_filter)
        self.sb_db_poly_order.setObjectName(_fromUtf8("sb_db_poly_order"))
        self.gridLayout_11.addWidget(self.sb_db_poly_order, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gb_display_b_error_filter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_11.addWidget(self.label_14, 2, 0, 1, 1)
        self.sb_db_sample_values = QtGui.QSpinBox(self.gb_display_b_error_filter)
        self.sb_db_sample_values.setObjectName(_fromUtf8("sb_db_sample_values"))
        self.gridLayout_11.addWidget(self.sb_db_sample_values, 2, 1, 1, 1)
        self.gridLayout_13.addWidget(self.gb_display_b_error_filter, 0, 1, 1, 1)
        self.gb_freq_error_filter = QtGui.QGroupBox(self.gb_error_filters)
        self.gb_freq_error_filter.setObjectName(_fromUtf8("gb_freq_error_filter"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gb_freq_error_filter)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_15 = QtGui.QLabel(self.gb_freq_error_filter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_12.addWidget(self.label_15, 0, 0, 1, 1)
        self.dsb_f_valid_range = QtGui.QDoubleSpinBox(self.gb_freq_error_filter)
        self.dsb_f_valid_range.setObjectName(_fromUtf8("dsb_f_valid_range"))
        self.gridLayout_12.addWidget(self.dsb_f_valid_range, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.gb_freq_error_filter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_12.addWidget(self.label_16, 1, 0, 1, 1)
        self.sb_f_poly_order = QtGui.QSpinBox(self.gb_freq_error_filter)
        self.sb_f_poly_order.setObjectName(_fromUtf8("sb_f_poly_order"))
        self.gridLayout_12.addWidget(self.sb_f_poly_order, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.gb_freq_error_filter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_12.addWidget(self.label_17, 2, 0, 1, 1)
        self.sb_f_sample_values = QtGui.QSpinBox(self.gb_freq_error_filter)
        self.sb_f_sample_values.setObjectName(_fromUtf8("sb_f_sample_values"))
        self.gridLayout_12.addWidget(self.sb_f_sample_values, 2, 1, 1, 1)
        self.gridLayout_13.addWidget(self.gb_freq_error_filter, 0, 2, 1, 1)
        self.tabWidget.addTab(self.config_inputs, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        HP4192A.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(HP4192A)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        HP4192A.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(HP4192A)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        HP4192A.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(HP4192A)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(HP4192A)
        self.tabWidget.setCurrentIndex(1)
        self.tbx_settings.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(HP4192A)

    def retranslateUi(self, HP4192A):
        HP4192A.setWindowTitle(_translate("hp4192a", "JMC hp4192a-LF DAQ", None))
        self.gb_plota.setTitle(_translate("hp4192a", "Plot A", None))
        self.gb_lcd_freq.setTitle(_translate("hp4192a", "Frequency", None))
        self.gb_plotb.setTitle(_translate("hp4192a", "Plot B", None))
        self.gb_lcd_a.setTitle(_translate("hp4192a", "Display A", None))
        self.gb_lcd_b.setTitle(_translate("hp4192a", "Display B", None))
        self.gb_plot_a_channels.setTitle(_translate("hp4192a", "Plot A", None))
        self.label.setText(_translate("hp4192a", "Eje X", None))
        self.cbx_x_plot_a.setItemText(0, _translate("hp4192a", "Display A", None))
        self.cbx_x_plot_a.setItemText(1, _translate("hp4192a", "Display B", None))
        self.cbx_x_plot_a.setItemText(2, _translate("hp4192a", "Frequency", None))
        self.label_2.setText(_translate("hp4192a", "Eje Y", None))
        self.cbx_y_plot_a.setItemText(0, _translate("hp4192a", "Display A", None))
        self.cbx_y_plot_a.setItemText(1, _translate("hp4192a", "Display B", None))
        self.cbx_y_plot_a.setItemText(2, _translate("hp4192a", "Frequency", None))
        self.gb_plot_b_channels.setTitle(_translate("hp4192a", "Plot B", None))
        self.label_3.setText(_translate("hp4192a", "Eje X", None))
        self.cbx_x_plot_b.setItemText(0, _translate("hp4192a", "Display A", None))
        self.cbx_x_plot_b.setItemText(1, _translate("hp4192a", "Display B", None))
        self.cbx_x_plot_b.setItemText(2, _translate("hp4192a", "Frequency", None))
        self.label_4.setText(_translate("hp4192a", "Eje Y", None))
        self.cbx_y_plot_b.setItemText(0, _translate("hp4192a", "Display A", None))
        self.cbx_y_plot_b.setItemText(1, _translate("hp4192a", "Display B", None))
        self.cbx_y_plot_b.setItemText(2, _translate("hp4192a", "Frequency", None))
        self.gb_impedance.setTitle(_translate("hp4192a", "Impedance", None))
        self.label_5.setText(_translate("hp4192a", "Area", None))
        self.cbx_impedance_area_units.setItemText(0, _translate("hp4192a", "cm2", None))
        self.cbx_impedance_area_units.setItemText(1, _translate("hp4192a", "mm2", None))
        self.cbx_impedance_area_units.setItemText(2, _translate("hp4192a", "um2", None))
        self.label_6.setText(_translate("hp4192a", "Thickness", None))
        self.cbx_impedance_thickness_units.setItemText(0, _translate("hp4192a", "cm2", None))
        self.cbx_impedance_thickness_units.setItemText(1, _translate("hp4192a", "mm2", None))
        self.cbx_impedance_thickness_units.setItemText(2, _translate("hp4192a", "um2", None))
        self.gb_capacitance.setTitle(_translate("hp4192a", "Capacitance", None))
        self.label_7.setText(_translate("hp4192a", "Area", None))
        self.cbx_capacitance_area_units.setItemText(0, _translate("hp4192a", "cm2", None))
        self.cbx_capacitance_area_units.setItemText(1, _translate("hp4192a", "mm2", None))
        self.cbx_capacitance_area_units.setItemText(2, _translate("hp4192a", "um2", None))
        self.label_8.setText(_translate("hp4192a", "Dielectric cte", None))
        self.cbx_capacitance_e0_units.setItemText(0, _translate("hp4192a", "cm2", None))
        self.cbx_capacitance_e0_units.setItemText(1, _translate("hp4192a", "mm2", None))
        self.cbx_capacitance_e0_units.setItemText(2, _translate("hp4192a", "um2", None))
        self.tbx_settings.setItemText(self.tbx_settings.indexOf(self.plot_settings), _translate("hp4192a", "Plot data settings", None))
        self.label_18.setText(_translate("hp4192a", "Select output file", None))
        self.label_20.setText(_translate("hp4192a", "Display B Order", None))
        self.tlb_output_file.setText(_translate("hp4192a", "...", None))
        self.label_19.setText(_translate("hp4192a", "Display A Order", None))
        self.tbx_settings.setItemText(self.tbx_settings.indexOf(self.save_data_settings), _translate("hp4192a", "Save data settings", None))
        self.pb_start.setText(_translate("hp4192a", "Start", None))
        self.pb_monitor.setText(_translate("hp4192a", "Monitor", None))
        self.pb_reset.setText(_translate("hp4192a", "Reset", None))
        self.tbx_settings.setItemText(self.tbx_settings.indexOf(self.control), _translate("hp4192a", "Control", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.experimental_setup), _translate("hp4192a", "Experimental Setup", None))
        self.gb_serial_config.setTitle(_translate("hp4192a", "RS232 Interface", None))
        self.lb_serial_stopbits.setText(_translate("hp4192a", "Stopbits", None))
        self.lb_serial_parity.setText(_translate("hp4192a", "Parity", None))
        self.lb_serial_bytesize.setText(_translate("hp4192a", "ByteSize", None))
        self.lb_serial_baudrate.setText(_translate("hp4192a", "Baudrate", None))
        self.lb_serial_timeout.setText(_translate("hp4192a", "Timeout", None))
        self.lb_serial_port.setText(_translate("hp4192a", "Serail Port", None))
        self.gb_error_filters.setTitle(_translate("hp4192a", "Error Filters", None))
        self.gb_display_a_error_filter.setTitle(_translate("hp4192a", "Display A", None))
        self.label_9.setText(_translate("hp4192a", "Valid data range (%)", None))
        self.label_11.setText(_translate("hp4192a", "Polynom order", None))
        self.label_12.setText(_translate("hp4192a", "Sample values", None))
        self.gb_display_b_error_filter.setTitle(_translate("hp4192a", "Display B", None))
        self.label_10.setText(_translate("hp4192a", "Valid data range (%)", None))
        self.label_13.setText(_translate("hp4192a", "Polynom order", None))
        self.label_14.setText(_translate("hp4192a", "Sample values", None))
        self.gb_freq_error_filter.setTitle(_translate("hp4192a", "Frequency", None))
        self.label_15.setText(_translate("hp4192a", "Valid data range (%)", None))
        self.label_16.setText(_translate("hp4192a", "Polynom order", None))
        self.label_17.setText(_translate("hp4192a", "Sample values", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config_inputs), _translate("hp4192a", "Config inputs", None))
        self.menuFile.setTitle(_translate("hp4192a", "File", None))
        self.actionQuit.setText(_translate("hp4192a", "Quit", None))

